# Preparation

Preparation biasa dilakukan untuk mempersiapkan data sebelum masuk dalam tahap pemodelan. <br>
Berikut adalah tahapan yang akan dilalui pada data `SC_HW1_bank_data.csv` sebelum tahap pemodelan :
1. Import Library
2. Input Dataset
3. Preprocessing
4. Train-Test Split

## Import Library

In [ ]:
import pandas as pd
import numpy as np

## Input Dataset

In [ ]:
#Membaca data dan memasukkannya ke dalam bentuk Pandas Dataframe
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')

In [ ]:
#Jalankan code untuk mengecek nama kolom yang tersedia
df.columns

Index(['RowNumber', 'CustomerId', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.head()

RowNumber  CustomerId Geography  Gender  Age  Tenure    Balance  \
0          1    15634602    France  Female   42       2       0.00   
1          2    15647311     Spain  Female   41       1   83807.86   
2          3    15619304    France  Female   42       8  159660.80   
3          4    15701354    France  Female   39       1       0.00   
4          5    15737888     Spain  Female   43       2  125510.82   

   NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0              1          1               1        101348.88       1  
1              1          0               1        112542.58       0  
2              3          1               0        113931.57       1  
3              2          0               0         93826.63       0  
4              1          1               1         79084.10       0

In [ ]:
#Hilangkan kolom yang dirasa tidak relevan dengan model (contoh: ID). None dapat diisi dengan nama-nama kolom yang akan digunakan.
#Contoh df = df[['X1','X2', 'Y']].copy()

#START CODE
df = df[['Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']].copy()

## Preprocessing

In [ ]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [ ]:
#Lakukan One-Hot Encoder untuk data categorical, dengan fungsi pandas get_dummies

#START CODE
df = pd.get_dummies(df)
df.head()

Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0   42       2       0.00              1          1               1   
1   41       1   83807.86              1          0               1   
2   42       8  159660.80              3          1               0   
3   39       1       0.00              2          0               0   
4   43       2  125510.82              1          1               1   

   EstimatedSalary  Exited  Geography_France  Geography_Germany  \
0        101348.88       1                 1                  0   
1        112542.58       0                 0                  0   
2        113931.57       1                 1                  0   
3         93826.63       0                 1                  0   
4         79084.10       0                 0                  0   

   Geography_Spain  Gender_Female  Gender_Male  
0                0              1            0  
1                1              1            0  
2                0              1            0  
3                0              1            0  
4                1              1            0

In [ ]:
#Pisahkan mana X (feature) dengan Y,
#Y adalah kolom "Exited"

#START CODE
X = df.drop('Exited', axis=1)
y = df['Exited']

In [ ]:
#Lakukan Scaler dan/atau Noermalisasi jika diperlukan
from sklearn.preprocessing import MinMaxScaler

#START CODE
scaler = MinMaxScaler()
X_transform = scaler.fit_transform(X)
X_transform

array([[0.32432432, 0.2       , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.31081081, 0.1       , 0.33403148, ..., 1.        , 1.        ,
        0.        ],
       [0.32432432, 0.8       , 0.63635718, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.24324324, 0.7       , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.32432432, 0.3       , 0.29922631, ..., 0.        , 0.        ,
        1.        ],
       [0.13513514, 0.4       , 0.51870777, ..., 0.        , 1.        ,
        0.        ]])

In [ ]:
#Ini digunakan jika dilakukan scaler/Normalisas. Jika tidak, code ini bisa dilewat dan diganti dengan code yang ada di dalam komen
X_transform = pd.DataFrame(X_transform, columns = X.columns)
X_transform
#X_transform = X.copy()

Age  Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     0.324324     0.2  0.000000       0.000000        1.0             1.0   
1     0.310811     0.1  0.334031       0.000000        0.0             1.0   
2     0.324324     0.8  0.636357       0.666667        1.0             0.0   
3     0.283784     0.1  0.000000       0.333333        0.0             0.0   
4     0.337838     0.2  0.500246       0.000000        1.0             1.0   
...        ...     ...       ...            ...        ...             ...   
9995  0.283784     0.5  0.000000       0.333333        1.0             0.0   
9996  0.229730     1.0  0.228657       0.000000        1.0             1.0   
9997  0.243243     0.7  0.000000       0.000000        0.0             1.0   
9998  0.324324     0.3  0.299226       0.333333        1.0             0.0   
9999  0.135135     0.4  0.518708       0.000000        1.0             0.0   

      EstimatedSalary  Geography_France  Geography_Germany  Geography_Spain  \
0            0.506735               1.0                0.0              0.0   
1            0.562709               0.0                0.0              1.0   
2            0.569654               1.0                0.0              0.0   
3            0.469120               1.0                0.0              0.0   
4            0.395400               0.0                0.0              1.0   
...               ...               ...                ...              ...   
9995         0.481341               1.0                0.0              0.0   
9996         0.508490               1.0                0.0              0.0   
9997         0.210390               1.0                0.0              0.0   
9998         0.464429               0.0                1.0              0.0   
9999         0.190914               1.0                0.0              0.0   

      Gender_Female  Gender_Male  
0               1.0          0.0  
1               1.0          0.0  
2               1.0          0.0  
3               1.0          0.0  
4               1.0          0.0  
...             ...          ...  
9995            0.0          1.0  
9996            0.0          1.0  
9997            1.0          0.0  
9998            0.0          1.0  
9999            1.0          0.0  

[10000 rows x 12 columns]

## Train-Test Split

In [ ]:
#Split menjadi train dan test dengan test_size 25%
#Tidak perlu mengubah code ini

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_transform,y,test_size = 0.25,random_state = 123)

# Modeling

## Model1

### Soal :
Jelaskan secara Singkat Model pertama yang digunakan!

Model yang pertama digunakan adalah Logistic Regression. Model ini digunakan untuk tugas klasifikasi, khususnya ketika Anda ingin memprediksi probabilitas terjadinya suatu peristiwa. Logistic Regression adalah salah satu algoritma klasifikasi yang paling sederhana dan umum digunakan. Model ini memodelkan hubungan antara variabel input dan probabilitas output dengan menggunakan fungsi logistik. Parameter yang diuji berupa 'C' (parameter regulasi), 'penalty' (jenis regulasi), 'solver' (algoritma penyelesaian), dan 'max_iter' (jumlah iterasi maksimum).

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


#START CODE
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
params1 = {
    'C': [0.01, 0.1, 1, 10, 100],  # Invers dari regulasi (semakin kecil semakin kuat regulasi)
    'penalty': ['l1', 'l2'],  # Jenis regulasi (L1 atau L2)
    'solver': ['liblinear', 'saga'],  # Solver yang digunakan
    'max_iter': [100, 200, 300],  # Jumlah iterasi maksimum
}
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(
             estimator= model1,
             param_grid= params1,
             scoring = 'accuracy',
             n_jobs = 10, # core cpu yang digunakan
             cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid.fit(X_train,y_train)
grid.best_params_

#1 menit 29 detik

{'C': 0.1, 'max_iter': 100, 'penalty': 'l1', 'solver': 'liblinear'}

In [ ]:
#lakukan evaluasi dengan beberapa maetric di bawah ini
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid.predict(X_test)

print("Classification Report : ")
print(classification_report(y_test,y_pred))

print("\nConfusion Matrix : ")
print(confusion_matrix(y_test,y_pred))

print("\nAccuracy Score : ")
print(accuracy_score(y_test, y_pred))

Classification Report : 
              precision    recall  f1-score   support

           0       0.82      0.98      0.89      1983
           1       0.68      0.19      0.29       517

    accuracy                           0.81      2500
   macro avg       0.75      0.58      0.59      2500
weighted avg       0.79      0.81      0.77      2500


Confusion Matrix : 
[[1938   45]
 [ 420   97]]

Accuracy Score : 
0.814


## Model2
### Soal :
Jelaskan secara Singkat Model ke-2 yang digunakan!

Model kedua yang digunakan adalah K-Nearest Neighbors (KNN): KNN adalah algoritma klasifikasi yang sederhana dan intuitif. Ide dasarnya adalah bahwa suatu data point diklasifikasikan berdasarkan mayoritas kelas dari tetangga terdekatnya dalam ruang fitur. Jadi, jika suatu data point memiliki tetangga-tetangga yang mayoritasnya termasuk dalam kelas A, maka data point tersebut akan diklasifikasikan ke dalam kelas A. Parameter yang diuji berupa 'n_neighbors' (jumlah tetangga terdekat yang akan dipertimbangkan), 'weights' (metode weighting), dan 'p' (parameter jarak).

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


#START CODE
from sklearn.neighbors import KNeighborsClassifier
model2 = KNeighborsClassifier()
params2 = {
    'n_neighbors': [3, 5, 7],  # Jumlah tetangga terdekat yang akan dipertimbangkan
    'weights': ['uniform', 'distance'],  # Metode weighting (seragam atau berdasarkan jarak)
    'p': [1, 2]  # Parameter jarak (1 untuk jarak Manhattan, 2 untuk jarak Euclidean)
}
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV
grid2 = GridSearchCV(
             estimator= model2,
             param_grid= params2,
             scoring = 'accuracy',
             n_jobs = 10, # core cpu yang digunakan
             cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid2.fit(X_train,y_train)
grid2.best_params_

#19 detik

{'n_neighbors': 7, 'p': 1, 'weights': 'distance'}

In [ ]:
#lakukan evaluasi
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid2.predict(X_test)

print("Classification Report : ")
print(classification_report(y_test,y_pred))

print("\nConfusion Matrix : ")
print(confusion_matrix(y_test,y_pred))

print("\nAccuracy Score : ")
print(accuracy_score(y_test, y_pred))

Classification Report : 
              precision    recall  f1-score   support

           0       0.85      0.95      0.89      1983
           1       0.63      0.34      0.45       517

    accuracy                           0.82      2500
   macro avg       0.74      0.65      0.67      2500
weighted avg       0.80      0.82      0.80      2500


Confusion Matrix : 
[[1879  104]
 [ 339  178]]

Accuracy Score : 
0.8228


## Model3
### Soal :
Jelaskan secara Singkat Model ke-3 yang digunakan!

Model ketiga yang digunakan adalah Support Vector Machine (SVM): SVM adalah algoritma klasifikasi yang kuat dan serbaguna yang digunakan untuk masalah klasifikasi dan regresi. SVM berusaha untuk menemukan hyperplane terbaik (garis atau permukaan) yang memisahkan dua kelas dalam ruang fitur. SVM dapat digunakan untuk masalah klasifikasi dengan dua kelas atau lebih, dan juga dapat diterapkan dalam ruang berdimensi tinggi. Parameter yang diuji berupa 'C' (parameter regulasi), 'kernel' (jenis kernel), dan 'gamma' (kernel coefficient).

In [ ]:
#Pilih salah satu metode Machine Leaarning
#Model Machine Learning dapat dipanggil terlebih dahulu melalui library yang digunakan. Gunakan library scikit learn seperti pada contoh

#Contoh pemanggilan library dan penggunaannya dalam model

#from sklearn.linear_model import LogisticRegression
#model1 = LogisticRegression()
#params = { "tol": [0.1,0.01,0.001], 'C':[0.5,1.0,1.5,2.0]}


#START CODE
from sklearn.svm import SVC
model3 = SVC()
params3 = {
    'C': [0.1, 1, 10],  # Parameter regulasi
    'kernel': ['linear', 'rbf', 'poly'],  # Jenis kernel (linear, radial basis function, polynomial)
    'gamma': ['scale', 'auto', 0.1, 1],  # Kernel coefficient
}
#END CODE

#Lakukan parameter tuning sesuai hyperparameter yang dibutuhkan
from sklearn.model_selection import GridSearchCV
grid3 = GridSearchCV(
             estimator= model3,
             param_grid= params3,
             scoring = 'accuracy',
             n_jobs = 10, # core cpu yang digunakan
             cv = 10 # 3-fold cross validation (artinya kita melakukan iterasi model sebanyak 3 kali)
            )

grid3.fit(X_train,y_train)
grid3.best_params_

{'C': 10, 'gamma': 1, 'kernel': 'poly'}

In [ ]:
#lakukan evaluasi
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = grid3.predict(X_test)

print("Classification Report : ")
print(classification_report(y_test,y_pred))

print("\nConfusion Matrix : ")
print(confusion_matrix(y_test,y_pred))

print("\nAccuracy Score : ")
print(accuracy_score(y_test, y_pred))

Classification Report : 
              precision    recall  f1-score   support

           0       0.87      0.98      0.92      1983
           1       0.82      0.44      0.57       517

    accuracy                           0.86      2500
   macro avg       0.85      0.71      0.75      2500
weighted avg       0.86      0.86      0.85      2500


Confusion Matrix : 
[[1934   49]
 [ 289  228]]

Accuracy Score : 
0.8648


## Tarik Kesimpulan Model Mana yang terbaik beserta alasannya

Dari 3 model yang telah saya buat, model ke-3 memiliki nilai akurasi terbesar. Model ke-3 menggunakan algoritma SVM. SVM dapat menangani data yang kompleks dan tidak linier serta cocok untuk ukuran data yang besar.